export const SERVICES: Service[] = [
  {
    id: 'svc-1',
    name: 'lambda-payment-auth',
    type: 'lambda',
    port: 4566,
    status: 'healthy',
    meta: 'Last invoked 2m ago · 142 inv/h',
    lastActivity: '2m',
  },
  {
    id: 'svc-2',
    name: 'sqs-order-processor',
    type: 'sqs',
    port: 4566,
    status: 'warning',
    meta: '0 Msg / 2 in DLQ',
    lastActivity: '8s',
  },
  {
    id: 'svc-3',
    name: 's3-user-avatars',
    type: 's3',
    port: 4566,
    status: 'healthy',
    meta: '1.2 GB · 482 objects',
    lastActivity: '—',
  },
  {
    id: 'svc-4',
    name: 'dynamodb-sessions',
    type: 'dynamodb',
    port: 4566,
    status: 'healthy',
    meta: '8 tables · 1.2k items',
    lastActivity: '12s',
  },
  {
    id: 'svc-5',
    name: 'sns-notifications',
    type: 'sns',
    port: 4566,
    status: 'healthy',
    meta: '3 topics · 7 subs',
    lastActivity: '1m',
  },
  {
    id: 'svc-6',
    name: 'lambda-image-resize',
    type: 'lambda',
    port: 4566,
    status: 'healthy',
    meta: 'Last invoked 14s ago',
    lastActivity: '14s',
  },
  {
    id: 'svc-7',
    name: 'sqs-email-queue',
    type: 'sqs',
    port: 4566,
    status: 'healthy',
    meta: '12 Msg / 0 DLQ',
    lastActivity: '3s',
  },
  {
    id: 'svc-8',
    name: 'secrets-api-keys',
    type: 'secrets',
    port: 4566,
    status: 'healthy',
    meta: '9 secrets stored',
    lastActivity: '—',
  },
  {
    id: 'svc-9',
    name: 's3-build-artifacts',
    type: 's3',
    port: 4566,
    status: 'healthy',
    meta: '240 MB · 3 buckets',
    lastActivity: '—',
  },
  {
    id: 'svc-10',
    name: 'lambda-webhook-router',
    type: 'lambda',
    port: 4566,
    status: 'offline',
    meta: 'Cold · no recent activity',
    lastActivity: '—',
  },
  {
    id: 'svc-11',
    name: 'sns-billing-events',
    type: 'sns',
    port: 4566,
    status: 'healthy',
    meta: '1 topic · 4 subs',
    lastActivity: '42s',
  },
  {
    id: 'svc-12',
    name: 'dynamodb-events-log',
    type: 'dynamodb',
    port: 4566,
    status: 'healthy',
    meta: '2 tables · 18.4k items',
    lastActivity: '1s',
  },
];
